# tic documentation: https://docs.ropensci.org/tic/dev/

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "if (!requireNamespace('remotes')) install.packages('remotes', type = 'binary')"
  - cmd: Rscript -e "if (getRversion() < '3.2' && !requireNamespace('curl')) install.packages('curl', type = 'binary')"
  - cmd: Rscript -e "options(pkgType = 'binary'); remotes::install_github('ropensci/tic', upgrade = 'always'); print(tic::dsl_load()); tic::prepare_all_stages()"

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# no testing on R-devel because no package binaries are available
environment:
  matrix:
    - R_VERSION: release
    - R_VERSION: oldrel
  id_rsa:
    secure: g3Kfde3Cu+CYLXiu69imcR8K0oAqfut2IbHOmx7w9i9Eg70AlxOp6SdCvPd88TmXFJauVVFk/sNv0LFx7cVc1dLzBgt7jujGPVdPMYvXAMaFfPxcHLdrjjpKezDmxqXBO4QVFi7cj/RhMDbxeUKOkw8BJWBJcegDJwXa/rytP9IkNgkM2AMg6/Vi0785b1NnRPekVHsAMHMNWxwAQ/XnFiheeVO0kmp/JbF8irhs+XsarL4DRPDWCkF0jxGHQvbJURPtq6iaUbaHH8UCFykYbBMeW7ZevsoDwKLD4UQ6+Y2nB9gelm6dIPFUfY12nEfznPlB7bc8Jdbbd7mktI+hjh+VMjlXrvhlkmafhg0Doh0yp+AhZEa9ePEvzqbFhh1ENTEmGzVOTV9N8J0owASgdWpBYMe2AGcBqsI/+12hhqIMVqxRNE16RCRz6nIWyMk4rmrLW5WGiIe8aGUB0QyIhnNZFvKceaIMzpLmIB72ZVh5YVn1JUj3g75ErAl6BhWi4p2W5kUVf3mihaU/aS2TbubuXxb9o7cEUao+sKVUM2b0YMV/gFXS+5ec7WT0bsS727UUVqX8lYE1lVO9Q18zWSEn4HRdzRrORBjN5oQtaK09zFLfbwyz5pUe/bZ9e8B4YVlpLRXpTI4MxVYfYwppBWCUXvK/3u5iA5GP6MJRzQYFjd6voZ3YP/qPi3cPdeP6asBegZgq57Fp+tRw71Crl3DnTrgeGEvErKVYoM1ltMhhaQD8O/wqSTc+OJwdPOGL9cApRo5/e9fmMk4/ldRQT/uJDiWcs7sTZPZXrKUwIrfzgxojYY23g9oa49ejtHCk2945FiRrG1oWlA7O+eCpioltkd4JRBXLSEvKTJTL0ZYg2+v3YaOUgMp+tILCHv20kTlP8A5e+axWa5naJwUC167pvvAVXaJZY48v6GXSaLmIoeR+VDvpJJEzktlZJdbrJ022aXRcNGjuOZURBQ2M7UTrYaWv9Sadq33u5rl29jqmhr4y2xij49kCXJeeF3q0RBiySJU73z9tVxqPzKZa1sRCn1ED8KL0lJiZYJH04/YmRfarxSc1SbIJyCVdyvnZUuxiDKLDj9QrVuFaeWG4oDe+tdGRBjNVOcQCODROmUOcaCZurc9tcQOByS6OznIinmXAupEHAvdOlyL1TW7517AfWNTKwHr51cNs4S+87zqMbDsjaROVOBcaB1CKneOKVT+r4UZuelQSskVluNvMN1cgwujpb+uUA7kz5Mu84Af4r4bD5lABYfk3FL5OYLUXnSUXk4hraP9hlhnnUKeptg0jI5n9WCYj3yCaA7deUC/ApgpdelXbHsX3Ta/RO9H9lvyfEd6HDdRIBSetPbDGU/pB/kQOEcRiKNRozZPs09bvMKc/5aHeNDaxIHJwRuBSX9pA8I+kMSVxrgXWLfLXoC/xMNk2N+Q5Xn+ve+e3mGGTTCvq1pL0USBm194uqUaBYjBdkVsvEf8vYl0lAubDb2MCgA8HZBwXsdBnO6Gvkb6aHlvG9nWQCE574lMD7n4nuBSuVwz69qB48LPFtAa1zqgBKyIAZwpLt9y7iLYGIpDwefQmnEN/VtDDCmAoDK5v3C2mWysQaYDJAHbCl04X3fiben3mp7jlYV4Kne/4jR1rfh8IH3ZdzOo/YVnmO8DwZGKC/c3Qlr5NQFst48TpOhaP60/djvGhTQF+AwUCqCLQV9e8SOCf13jWOi0FHxQs+UuOTV4WvJtpo7EBQ5XPxZgcJpchppDrMLMcDtrNd73pSNM2ZPicnCavBcrJpCxO6j8nvh7lXX81TeQI+uNFbNMamlQXCryHTAcmjbpUn/vYn6aWdWL2lCUNHALoL8QUcwxMF1b6ZcTP6Vjd7lyj8qZ/VxSLyIVeZy7DnVbYYoq40a2AbNkbRcZ2xXhFOZx5nmJigaHB51rsyjRomiuPWmnBWqibmoh/GTcURmQAC9qWikcNNP2cXXPQRKbQfTPWWoZx8dSoUkXo5lQiW3SDmX0V15VeomUY3FPWc4SGfp0j7wP02/U/ie29qD1y2dsMUpHOsMzZS3MfPPc2nUsAuS5MR0HO+wBw8IdY8iIKMe7GbkI9fKXbzIX/ujtFmOqFwBgmGJGTIM+geQ+7fGUqiXuEwJ/bGh5xjPAp1dV2U4z+cBADvFYzLEs1efa3nXRAWqTTQU6CX0Pknu3vWjcTg95qhgSTqoo1lFNf7D7zenJNUcVRYIlkjAg1uQAn3Hnt8qEZHuFpHuXcq/iqfVReiahVoHFFhMGjyVRa6U8vD60nGEacx8ipCEdP/2O+JpqNApNf2FoXZ7FK9KsRTceCJGIc6aMafUtoum2LGfRPWl8h1MEioGubpuuyylDKs8fCYALMYXAdqr2fhioWgmGiB/bytPJr6cFPdMa1D4X8ObJoMxAdl4M8o3wnf3MqW0qnP19uXueTuGqMuZ91lYcUi5eOZ6gnUeDj9zjRiQkMGJ0aDEDFMvhUeK5ztRgBK3nosuLCr8btjW6rHUdABWpIchYKkNhXfiVO9dvwuujGtxNKHWz8tX4tYeTPhiAGmehqddUe1EmV9BGGNg9b8CKQ2WA/acl6PR/HtFGbb0/vSxUvxHt52cjae8BOqFbpwMa73GyrbKPMfFwa6DDfNBbtalUPR+FURtK9x6JyzZhYx6NnJhzj9MUq1KpZIMmuN3TksCA544RdkY43pwWkeeslyUUmHN78DibjCMV55bDiuecFgXCXkLRBwQMNxf8FZQ/qmeh/AXFRrxUgpVRNcbYSVxAQT+cVpUTuRl1T1cqEguoPncvgkRmBasONUeCiLrmALNvsUrQC3+p/loZ8uajZA463J20OWXm9ytNCBjzDCgBTuvEJbtIiuh+eEgNesIjg9yIRJc2Mo6pIRQwyKbr3hHtXTkCqnuzRN4+Xr6Gl0kmphktvhD2zv8oKwU8mL431aKvNnkgQlPkbsUtd3p8/jnjf430mqpa8qwlveg5CfyX1ms+YhC7C1vZFT9XzJwBfkgtnUskOvmYfv+cRwdVKOoT5kla/lAyN5+OZOXrgATc=
  USE_RTOOLS: true

matrix:
  fast_finish: true
# Custom user code -------------------------------------------------------------
